apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T05:33:41Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4521"
  uid: 5e63ae8a-edeb-4ff8-bb0c-ee0297edbf28
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.120.152
  clusterIPs:
  - 10.103.120.152
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30338
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
